kind: Deployment
metadata:
  name: resume-rank-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-rank-gke
  template:
    metadata:
      labels:
        app: resume-rank-gke
    spec:
      containers:
      - name: resume-rank-gke
        image: gcr.io/resume-rank-system/resume-rank-gke:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"